FROM balenalib/amd64-alpine

ARG BUILD_DATE
ARG BUILD_VERSION

LABEL build_version="${BUILD_VERSION}"
LABEL build_date="${BUILD_DATE}"
LABEL maintainer="kylemharding@gmail.com"

# install packages
RUN install_packages \
	ca-certificates \
	curl \
	bind-tools \
	unbound

# install default config file
WORKDIR /etc/unbound/unbound.conf.d
COPY default.conf .

# copy startup script
WORKDIR /var/lib/unbound
COPY start.sh .

# run start script on boot
CMD ["bash", "start.sh"]
