#!/bin/bash -xe

env

docker build "$@" \
	--build-arg "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
	--build-arg "BUILD_VERSION=$(./version.sh "${DOCKERFILE_PATH}")" \
	--build-arg "VCS_REF=$(git describe --tags --long --dirty --always)" \
	--file "${DOCKERFILE_PATH}" \
	--tag "${IMAGE_NAME}" \
	.